version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: induslink
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: induslinkdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: securepassword
    volumes:
      - influxdb_data:/var/lib/influxdb

  opcua-server:
    image: chrismsimpson/milo-opcua-server:latest
    container_name: opcua-server
    restart: always
    ports:
      - "4840:4840"
volumes:
  postgres_data:
  influxdb_data:
